### ISSUE TITLE
Parameterize VPC, Subnet & DNS record

### ISSUE THREAD

**Issue by chrisammon3000** [nmdp-bioinformatics/gfe-db#86]
## Description
The current networking configuration deploys a new VPC, public subnet and creates a new A record for an existing hosted zone (identified by the domain name).

This will make the following changes:
* Batch jobs and Neo4j will use an existing VPC and public subnet based on their id values passed as parameters at deploy time
* When the database stack is deployed, it will update the the resource records of an existing A record set on an existing hosted zone using AWS CLI commands and orchestrated by Makefile targets

*Note: * It will be possible to change the subnet from public to private at a later point once these changes are tested

### Environment Variables
These environment variables are added:
```env
VPC_ID=vpc-8a3d74f0
PUBLIC_SUBNET_ID=subnet-5c44793b
```
These environment variables already existing but are being handled by different logic (Makefile targets)
```env
HOST_DOMAIN=cloudftl.com
SUBDOMAIN=dev-gfe-db
```

## References
AWS::Route53::RecordSet resource ([link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-resourcerecords))

Current configuration:
```yaml
# ./gfe-db/database/template.yaml
  Neo4jDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${HostDomain}." 
      Comment: !Sub 'DNS name for ${Stage}-${AppName} server'
      Name: !Sub ${Subdomain}.${HostDomain}. # HostDomain and Subdomain are passed as env vars at deploy time
      Type: A
      TTL: 300
      ResourceRecords:
      - !Sub '{{resolve:ssm:/${AppName}/${Stage}/${AWS::Region}/Neo4jDatabaseEndpoint}}' # This value is available once Neo4j is running
```
